### ISSUE TITLE
icons for ibuffer groups 

### ISSUE THREAD

**Issue by mohkale** [seagle0128/all-the-icons-ibuffer#3]
In the screenshot, groups have a folder icon prefixed to them, this isn't happening in my ibuffer. Is it implemented somewhere else.

![screenshot](https://user-images.githubusercontent.com/140797/73564021-b1afe080-4499-11ea-87da-e2fa32d18f53.png)

**Comment by seagle0128** [comment]
I am using [ibuffer-projectile](https://github.com/purcell/ibuffer-projectile). You need to customize `ibuffer-projectile-prefix`. 
My configurations are [Centaur Emacs](https://github.com/seagle0128/.emacs.d).

**Comment by mohkale** [comment]
I see, thnx for the update 😄.

Here's the exact code from your config in case someone stumbles on this in future.

```elisp
(setq ibuffer-projectile-prefix
        (if (icons-displayable-p)
            (concat
             (all-the-icons-octicon "file-directory"
                                    :face ibuffer-filter-group-name-face
                                    :v-adjust -0.05
                                    :height 1.25)
             " ")
          "Project: "))
```
