### ISSUE TITLE
Typo in install instructions in help?

### ISSUE THREAD

**Issue by mrspeaker** [seagle0128/all-the-icons-ibuffer#4]
I looked up this package from package-install and copy/pasted the "use-package" instructions for installing - but I think there's a typo: https://github.com/seagle0128/all-the-icons-ibuffer/blob/master/all-the-icons-ibuffer.el#L38

It says `(use-package all-the-icons-ibuffer-mode` when I think it should just be `(use-package all-the-icons-ibuffer`?

(Also, thanks for the package!)

**Comment by seagle0128** [comment]
Thank you! It's a typo issue. Will fix it right now.
