### ISSUE TITLE
Show total size in human readable form in summary line.

### ISSUE THREAD

**Issue by fernandodemorais-jf** [seagle0128/all-the-icons-ibuffer#5]
Hello,

The total size of the buffers, displayed in the bottom summary line, is not being calculated and displayed correctly, even if you set `(all-the-icons-ibuffer-human-readable-size t)`. This error can be seen in package screenshot.

Reading your code, I saw that the file sizes are converted to floats, and then summed, without making the correct calculation of its sizes, according to the dimension prefix (k, M, G, etc.).

So, inspired by the code of the `file-size-human-readable` function, I came up with this function:

```elisp
(defun jfmf/file-size-human-readable-to-bytes (file-size &optional flavor)
      "Convert a human-readable file size string into bytes."
      (let ((power (if (or (null flavor) (eq flavor 'iec))
		       1024.0
		     1000.0))
	    (prefixes '("k" "M" "G" "T" "P" "E" "Z" "Y"))
	    (iterator 0))
	(catch 'bytes
	  (while
	      (cond
	       ((equal iterator 8)
		(throw 'bytes (* (string-to-number file-size) (expt power 0))))
	       ((string-match (elt prefixes iterator) file-size)
		(throw 'bytes (* (string-to-number file-size) (expt power (1+ iterator)))))
	       (t
		(setq iterator (1+ iterator))))))))
```

There may be a more appropriate way to do this, but this function already manages to supply what is needed.

That way, `define-ibuffer-column size-h`, in `all-the-icons-ibuffer` code, would look like this:

```elisp
(define-ibuffer-column size-h
  (:name "Size"
   :inline t
   :props ('font-lock-face 'font-lock-comment-face)
   :header-mouse-map ibuffer-size-header-map
   :summarizer
   (lambda (column-strings)
     (let ((total 0))
       (dolist (string column-strings)
	     (setq total
	           ;; like, ewww ...
	           (+ (float (jfmf/file-size-human-readable-to-bytes string))
		          total)))
       (file-size-human-readable total))))
  (let ((size (buffer-size)))
    (if all-the-icons-ibuffer-human-readable-size
        (file-size-human-readable size)
      (format "%s" size))))
```

Thanks!

**Comment by seagle0128** [comment]
You are right! I am fixing it.
