### ISSUE TITLE
Remove forced autoloads

### ISSUE THREAD

**Issue by mohkale** [seagle0128/all-the-icons-ibuffer#6]
The autoloads in this package seem to specify you can find function definitions for `ibuffer-make-column-icon` and various others but on my `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.26, cairo version 1.17.4) of 2021-03-04` it keeps throwing an error on load because those functions aren't actually defined. For now I've changed my `straight` recipe to avoid autoloads `(all-the-icons-ibuffer :build (:not autoloads))` but I'd prefer if they were removed from here if their not necessary.

**Comment by seagle0128** [comment]
Can you provide the detailed errors? I didn't get any error in my env.

**Comment by mohkale** [comment]
@seagle0128 

I see you've removed the autoloads as I asked? Did you manage to reproduce? or would you still like me to share the error message?

**Comment by seagle0128** [comment]
@mohkale I've removed the autoloads. No need to provide any info. Please help to test. Thanks!

**Comment by mohkale** [comment]
@seagle0128 

Can confirm, no errors on loading now. Thank you.
