### ISSUE TITLE
Remove display-graphic-p from icon checks

### ISSUE THREAD

**Issue by mohkale** [seagle0128/all-the-icons-ibuffer#7]
I've got icons setup on my terminal but this plugin doesn't render them because it actively disables them on non GUI frames ([here](https://github.com/seagle0128/all-the-icons-ibuffer/blob/f689582a413ba5bb722067ea470829819e1f1131/all-the-icons-ibuffer.el#L110) and [here](https://github.com/seagle0128/all-the-icons-ibuffer/blob/f689582a413ba5bb722067ea470829819e1f1131/all-the-icons-ibuffer.el#L114)). It should be sufficient to have end-users disable `all-the-icons-ibuffer-icon` on non graphical frames if they don't want them so there's no need for the plugin to do so as well.

**Comment by seagle0128** [comment]
It's as designed since `all-the-icons` doesn't support terminal well.

**Comment by mohkale** [comment]
@seagle0128 

> It's as designed since all-the-icons doesn't support terminal well.

I agree it's a little more of a hassle but it's certainly not unsupported or unusable. 

![Screenshot_20211021_160926](https://user-images.githubusercontent.com/23294780/138306364-f34ef29d-5407-40a6-8db1-1978d11f2287.png)

Either way the way this plugin has implemented it there's no way to use `all-the-icons-ibuffer-mode` on terminal frames. That's probably a good move for most users, but I think taking the abilitiy away to use them altogether for other users is a bad choice. If users don't want icons on terminal frames they should `(setq all-the-icons-ibuffer-icon (display-graphic-p))` (or perhaps we should make the `defcustom` default to that).

Edit: Technically I'm not using that mode so this isn't an issue for me, instead I'm just setting `ibuffer-formats` manually and using the icon column defined by this package. I didn't realise I had setup a custom variable for showing icons when I made this issue so if you don't want to change the behaviour that's fine, I just thought there's little value in having the check.

**Comment by seagle0128** [comment]
Thanks for the update! I am curious how do you use `all-the-icons` in terminal mode? What OS and version?

**Comment by mohkale** [comment]
@seagle0128 

> how do you use all-the-icons in terminal mode? What OS and version?

I'm on linux, using st (here's my [fork](https://github.com/mohkale/st/)) a lightweight terminal built for the X window system. If you look in my [fonts](https://github.com/mohkale/st/blob/d81ff8c7d711b17ff917a7ddddd4035fd076b390/config.h#L8) config for st you'll find I've added all the all-the-icons fonts as sparefonts meaning when my terminal tries to render a glyph not in my main font, it tries each font in sparefonts until it finds one that has the glyph. Thats' the terminal side, and it works reasonably well, however because all-the-icons uses multiple fonts there's a high chance a glyph will conflict between them. For example my octicon icon for repository is a clock due to how my font lookup precedence works. To get around that I'm using [nerd-fonts](https://github.com/mohkale/nerd-fonts.el) (these have the highest priority in my terminal lookup) and then replacing any references to an all-the-icons font (eg: octicon) with the equivalent nerd-font (eg: nerd-oct). This is configured [here](https://github.com/mohkale/emacs/blob/master/init.org#nerd-fonts). Lastly since most icons are double width (they take up the size of two characters when rendered) I've had to advise several functions to add another space when on terminal frames. For example [this](https://github.com/mohkale/emacs/blob/master/init.org#ibuffer-all-the-icons) is how I do it with this package, or on some functions I just [advise](https://github.com/mohkale/emacs/blob/master/init.org#all-the-icons-dired) all the `all-the-icons-%s` family functions to be suffixed such as on `all-the-icons-dired`. This last point isn't ideal since some packages don't expose the functionality for advising how they insert a icon. For example I've managed to advise dashboard to properly pad icons in the headers (recent files, projects, etc.) but can't figure out a way to do so for the contents (the org icon for example should have an extra space before the `~/` but it doesn't.

![Screenshot_20211023_153128](https://user-images.githubusercontent.com/23294780/138560694-756fab27-0970-41e2-843b-ad7de9f9fc66.png)


Here's my [emacs config](https://github.com/mohkale/emacs) in case you want some more screenshots of icons on the terminal.

**Comment by seagle0128** [comment]
@mohkale Thanks for your sharing! I've understood your solution completely. It would be better if you make a separate package.

**Comment by mohkale** [comment]
You mean fork ibuffer-all-the-icons? Or create a package that bridges the gap between nerd fonts and all-the-icons?

The latter I've avoided since there's a pending issue in the nerd font package that I'm waiting on the maintainer to resolve.

**Comment by seagle0128** [comment]
I mean the latter. And I found some icons are missing in nerd font, e.g. emacs. Is it still an issue?

And I recalled, should consider this case: the user is using both terminal and GUI, but the icons don't work in terminal. The current solution is able to work.

**Comment by mohkale** [comment]
> e.g. emacs. Is it still an issue?

Yep, their really taking their time on it. :disappointed:.

> the user is using both terminal and GUI, but the icons don't work in terminal. The current solution is able to work.

I mean I can do that?

![Screenshot_20211030_162646](https://user-images.githubusercontent.com/23294780/139539418-e520cff1-8679-4fee-bb11-e5a1f430c99d.png)

In the end my opinion on this is if you have a more complex workflow, you should configure it to handle that. If you can only support icons on graphical frames then don't use the terminal, or don't enable icons on either. You could even setup a hook that detects when a new frame is made and disables icons on all frames based on whether its on the terminal or the GUI. Hard-coding a dependence on a specific front-end is a bad idea. Consistency across GUIs and TTYs is one of emacs strong points.

EDIT: Also correct me if I'm wrong but display-graphic-p doesn't stop icons being inserted in tty frames? It's not as if ibuffer is refreshed when you visit an existing buffer from a terminal frame. For example I can make the ibuffer on a graphical frame, make a new tty frame and then switch-buffer to it and the icons would still be there.

**Comment by mohkale** [comment]
Hi. A recent change to this project has invalidated the workaround I had in my config... so I'm asking again, please don't disable icons on terminal frames. The new implementation is baked directly into the minor mode so now I can't workaround it without advising away `display-graphic-p` within `all-the-icons-ibuffer-mode` or redefining the minor mode verbatim just without `display-graphic-p`.

**Comment by seagle0128** [comment]
Right! I made a break change recently, to support daemon mode. Please see https://github.com/seagle0128/all-the-icons-ibuffer/issues/9#issuecomment-1106361141.

**Comment by mohkale** [comment]
@seagle0128 

I can see why you made it a minor mode and I agree it makes sense. I don't see why you're still preventing the mode from being used in terminal frames when I've demonstrated it works fine. Could you at the very least move it to an option I can disable. Something like `(defcustom ibuffer-all-the-icons-display-predicate #'display-graphic-p)`.

**Comment by seagle0128** [comment]
@mohkale I know it's possible to display the icons in the terminal. Are you using [icons-in-terminal](https://github.com/sebastiencs/icons-in-terminal) or something else? 

[all-the-icons](https://github.com/domtronn/all-the-icons.el) doesn't support terminal officially, so `all-the-icons-ibuffer` doesn't, either.  `all-the-icons` is used in multiple platform including Linux, macOS and Windows. If removing `display-grahpic-p`,  users will see lots of wired characters, especially on Windows/Cygwin. I don't want to handle such issues.

> (defcustom ibuffer-all-the-icons-display-predicate #'display-graphic-p)

But this may be a good idea!

**Comment by mohkale** [comment]
> I know it's possible to display the icons in the terminal. Are you using [icons-in-terminal](https://github.com/sebastiencs/icons-in-terminal) or something else?

I'm using all-the-icons. Perhaps scroll through the history of this issue ticket (it's been a while so I'd understand if you've forgotten). Since then I've also created a new package [all-the-icons-nerd-fonts](https://github.com/mohkale/all-the-icons-nerd-fonts) which contains the bulk of my configuration.

> users will see lots of wired characters.

Which is an issue with their terminal configuration, not this package. Most terminal users would understand this (and barring that you can include a section in the README mentioning it). I'm fine with you disabling terminal support out of the box, that's likely a reasonable default, but atm there's no convenient way to enable it for terminal users which is my issue. 

> But this may be a good idea!

Great. PR incoming.

**Comment by seagle0128** [comment]
The pactch 0c72213 has been commit.

**Comment by mohkale** [comment]
> Great. PR incoming.

Ah, you're too fast for me. Thanks a bunch :-).

**Comment by seagle0128** [comment]
@mohkale Welcome. When [all-the-icons-nerd-fonts](https://github.com/mohkale/all-the-icons-nerd-fonts) will be released to MELPA? And I remember some icons are missing in nerd fonts, e.g. Emacs 😢

**Comment by mohkale** [comment]
> When [all-the-icons-nerd-fonts](https://github.com/mohkale/all-the-icons-nerd-fonts) will be released to MELPA

Ideally when [nerd-fonts#2](https://github.com/twlz0ne/nerd-fonts.el/issues/2) is fixed. That's been open for over a year so I'm not sure whether the nerd-fonts package is even still actively maintained. I could likely add a workaround in my package but it'd require some testing. If nerd-fonts itself isn't updated soon that's likely what I'd do, it's in my backlog.

> And I remember some icons are missing in nerd fonts, e.g. Emacs

Yes. Still an issue. It's not one I've faced yet since nothing in my nerd-fonts font conflicts with the emacs icon and I've got all of all-the-icons fonts in my lookup as well. To demonstrate you can take a look at my tmux status-line which has the emacs icon right there :-).

![Screenshot_20220424_113728](https://user-images.githubusercontent.com/23294780/164972474-f409a8db-7334-4f10-8ae8-03649bb3a4e0.png)

**Comment by seagle0128** [comment]
Oh, thanks for the info. I will try nerd fonts, again.

**Comment by mohkale** [comment]
Great. If you're gonna try out all-the-icons-nerd-fonts any feedback would be appreciated :-).

For [reference](https://github.com/mohkale/st/blob/5fbb15b8c48041c5ed92637d9444457e2c0b1210/config.def.h#L8) here's the list of fonts I have and the order in which their configured. In way of terminals I'd recommend kitty. It has really nice font support letting you specify which individual glyphs you want from a font. It also has this really cool feature that shrinks a multi-character glyph to fit. So if you have a 2-character width icon it gets followed by a space it's shown as two characters, if you don't have the space it's resized and shown as a single character. In my terminal it just cuts off the icon at the halfway point :cry:. I'll create a patch for st for this at some point as well :-).

**Comment by seagle0128** [comment]
Unfortunately I got this screenshot 😢 

The folder icon is correct, but still no emacs icon for me

<img width="399" alt="image" src="https://user-images.githubusercontent.com/140797/164973653-ae9b1209-d711-4d08-8da6-1c0ae172ee0e.png">

**Comment by mohkale** [comment]
Could you share which terminal you're using and what configuration (if any) you have for it?

**Comment by seagle0128** [comment]
I am using iterm2 with Hack Nerd Fonts on macOS. No special configurations.

**Comment by mohkale** [comment]
Hmmm... I can't really reproduce since I don't have a mac-os machine :/. I'd suggest making sure the right fonts are in the lookup. The question mark glyph shown there is often used when your terminal doesn't have any fonts with the glyph in its lookup.

Edit: Looks like iterm doesn't [support font-fallbacks](https://gitlab.com/gnachman/iterm2/-/issues/3403). I'd suggest trying a terminal that can like mine (st) or one you can configure to like kitty.

**Comment by seagle0128** [comment]
What fonts are you using for the fallbacks? I think there is no emacs icon in the latest nerd fonts.

See https://github.com/ryanoasis/nerd-fonts/issues/342.

**Comment by mohkale** [comment]
I linked it [above](https://github.com/mohkale/st/blob/5fbb15b8c48041c5ed92637d9444457e2c0b1210/config.def.h#L8). font is the main font, then it goes through each font in sparefonts until it finds one with an entry for the current glyph.

**Comment by seagle0128** [comment]
Oh, I see. You are using st which is built by yourself. The solution seems not working for other terminals, unless building all fonts into one, IMO.

Edit: I added this to `all-the-icons-nerd-fonts-convert-icons`, it looks good. The only problem is the nerd-dev icons are much smaller. This  seems the best common solution for missing icons, at least to me.

```elisp
    ((all-the-icons-fileicon   . "elisp")            .    (all-the-icons-nerd-dev    . "gnu"))
    ((all-the-icons-fileicon   . "emacs")            .    (all-the-icons-nerd-dev    . "gnu"))
```

<img width="396" alt="image" src="https://user-images.githubusercontent.com/140797/165011341-97412a5c-73f4-4d86-aca4-d63b8e3b82cf.png">

**Comment by mohkale** [comment]
> it looks good. The only problem is the nerd-dev icons are much smaller.

You should be able to configure the scaling for individual fonts. In my case they were too big so I scaled them down a bit.

> I added this to all-the-icons-nerd-fonts-convert-icons

Why would you replace the emacs and elisp icons with GNU ones? Personally I prefer them staying as they are.

**Comment by seagle0128** [comment]
> Why would you replace the emacs and elisp icons with GNU ones? Personally I prefer them staying as they are.

Because there is no emacs or elisp icon in nerd-fonts. I have to use gnu icon instead, for testing purpose.
