### ISSUE TITLE
Broken in Emacs-Client on Windows

### ISSUE THREAD

**Issue by technician77** [seagle0128/all-the-icons-ibuffer#8]
Below are two screenshots both use identical configuration, the only difference is that the one with the icons is using the full emacs.exe the other one is using the emacs-client.exe. I use the latest emacs 28 from 2022-02-13, but the problem is also visible on latest stable emacs 27. Any idea?
<img width="697" alt="GoodCase" src="https://user-images.githubusercontent.com/18722291/154836860-6fe6a41d-1db4-4ec0-86b6-0b90d0120ea3.png">
<img width="681" alt="BadCase" src="https://user-images.githubusercontent.com/18722291/154836866-474fb78d-c1c9-46c9-9297-3c31c617dd2b.png">

**Comment by seagle0128** [comment]
It's as designed. The icons depend on `(display-graphic-p)` and `all-the-icons-ibuffer-icon`.

If you are using emacsclient on Windows GUI, try this solution.

```elisp
(setq all-the-icons-ibuffer-formats
  `((mark modified read-only ,(if (>= emacs-major-version 26) 'locked "")
          " " ,(if (and (display-graphic-p)
                        all-the-icons-ibuffer-icon)
                   '(icon 2 2 :left :elide)
                 "")
          ,(if (and (display-graphic-p)
                    all-the-icons-ibuffer-icon)
               (propertize " " 'display `(space :align-to 8))
             "")
          (name 18 18 :left :elide)
          " " (size-h 9 -1 :right)
          " " (mode+ 16 16 :left :elide)
          " " filename-and-process+)
    (mark " " (name 16 -1) " " filename))
)
(setq ibuffer-formats all-the-icons-ibuffer-formats)
```

**Comment by technician77** [comment]
Thanks for the effort, but I get `ibuffer-expand-format-entry: Unknown column (if (>= emacs-major-version 26) 'locked ) in ibuffer-formats` and the ibuffer is empty.
`all-the-icons-ibuffer-icon` is true for full emacs and emacs-client. The function `(display-graphic-p)` seems to exist also in both versions

**Comment by seagle0128** [comment]
You should change the snippet slightly according to your env like this:

```elisp
(setq all-the-icons-ibuffer-formats
  `((mark modified read-only locked
          " " ,(if (and (display-graphic-p)
                        all-the-icons-ibuffer-icon)
                   '(icon 2 2 :left :elide)
                 "")
          ,(if (and (display-graphic-p)
                    all-the-icons-ibuffer-icon)
               (propertize " " 'display `(space :align-to 8))
             "")
          (name 18 18 :left :elide)
          " " (size-h 9 -1 :right)
          " " (mode+ 16 16 :left :elide)
          " " filename-and-process+)
    (mark " " (name 16 -1) " " filename))
)
(setq ibuffer-formats all-the-icons-ibuffer-formats)
```

**Comment by technician77** [comment]
Great, that works. Thanks for your effort.
