### ISSUE TITLE
Icons don't show when emacs client launched via daemon/server

### ISSUE THREAD

**Issue by zmberber** [seagle0128/all-the-icons-ibuffer#9]
When launching Emacs normally, the icons show up just fine.  When starting an Emacs server/daemon and launching a client, the icons don't show in an ibuffer buffer.

## System information

- Kernel 5.16.10-arch1-1
- GNU Emacs 27.2

## Steps to reproduce on unconfigured GNU Emacs 27.2

1.  Open Emacs and install the `all-the-icons-package` with `package.el` from MELPA.
2.  Execute `all-the-icons-install-fonts` (and confirm)
3.  Put the following in `~/.emacs.d/init.el`:
    
    ```elisp
    (when (display-graphic-p)
      (require 'all-the-icons))
    (all-the-icons-ibuffer-mode 1)
    ```
4.  Start an emacs server with `emacs --daemon`
5.  Start an emacs client with `emacsclient -c`
6.  Inside that emacs client, open an ibuffer buffer with `M-x ibuffer`

### Expected behaviour

Visible icons for every listed buffer in the ibuffer buffer

### Actual behaviour

No visible icons for any listed buffer in the ibuffer buffer

**Comment by seagle0128** [comment]
It's as designed. See workaround [here](https://github.com/seagle0128/all-the-icons-ibuffer/issues/8#issuecomment-1048965095).

**Comment by zmberber** [comment]
I put the following, as you suggested, into my `init.el`.

```elisp
(setq all-the-icons-ibuffer-formats
  `((mark modified read-only ,(if (>= emacs-major-version 26) 'locked "")
          " " ,(if (and (display-graphic-p)
                        all-the-icons-ibuffer-icon)
                   '(icon 2 2 :left :elide)
                 "")
          ,(if (and (display-graphic-p)
                    all-the-icons-ibuffer-icon)
               (propertize " " 'display `(space :align-to 8))
             "")
          (name 18 18 :left :elide)
          " " (size-h 9 -1 :right)
          " " (mode+ 16 16 :left :elide)
          " " filename-and-process+)
    (mark " " (name 16 -1) " " filename))
)
(setq ibuffer-formats all-the-icons-ibuffer-formats)
```

It doesn't work.  But if I execute this after I start a client from the server, then the icons do work.

**Comment by seagle0128** [comment]
You should put the snippet in `with-eval-after-load` form.

**Comment by zmberber** [comment]
thanks for the reply!

okay, what should i best load it after?

**Comment by zmberber** [comment]
I found a solution:

```elisp
(defun my-all-the-icons-ibuffer ()
  (setq all-the-icons-ibuffer-formats
	`((mark modified read-only locked
		" " ,(if (and (display-graphic-p)
			      all-the-icons-ibuffer-icon)
			 '(icon 2 2 :left :elide)
		       "")
		,(if (and (display-graphic-p)
			  all-the-icons-ibuffer-icon)
		     (propertize " " 'display `(space :align-to 8))
		   "")
		(name 18 18 :left :elide)
		" " (size-h 9 -1 :right)
		" " (mode+ 16 16 :left :elide)
		" " filename-and-process+)
	  (mark " " (name 16 -1) " " filename))
	)
  (setq ibuffer-formats all-the-icons-ibuffer-formats))
(add-hook 'server-after-make-frame-hook 'my-all-the-icons-ibuffer)
```

I don't know if this is good practise, this gets loaded for each new frame if I understand it correctly.  But it is only needed to be executed once.

Curious to know with what I can `with-eval-after-load` to make it work as you suggest.

**Comment by seagle0128** [comment]
Using `server-after-make-frame-hook` is a correct solution for this scenario.

**Comment by seagle0128** [comment]
Break changes in 8754cca. Please reconfigure it as below.

```elisp
(add-hook 'ibuffer-mode-hook #'all-the-icons-ibuffer-mode)
;; or
(use-package all-the-icons-ibuffer
  :ensure t
  :hook (ibuffer-mode . all-the-icons-ibuffer-mode))
```
